### ISSUE TITLE
Mastodon logo on HP?

### ISSUE THREAD

**Issue by DanBIF** [gbif/gbif-web#1011]
Hi, on the danish HP there is still logo and link to "X"
Have you impleneted a logo for Mastodon for the HP's like you have for gbif.org? - and if yes, how do I get that update to my HP?
I have account to link to when I have the logo :-)
https://biodiversity.social/@DanBIF

**Comment by MortenHofft** [comment]
Just add `mastodon_url: https://biodiversity.social/@DanBIF` to your `_config.yml`

options
```yaml
# SOCIAL PROFILES
email: info@gbif.org                              # Social icon in footer
twitter_username: gbif                            # Social icon in footer
github_username: gbif                             # Social icon in footer
bluesky_username: gbif.org                        # Social icon in footer
youtube_username: gbif                            # Social icon in footer
facebook_username: gbif                           # Social icon in footer
flickr_username: gbif                             # Social icon in footer
instagram_username: gbifs                         # Social icon in footer
mastodon_url: https://biodiversity.social/@gbif   # Social icon in footer
linkedin_url: https://www.linkedin.com/company/gbif # Social icon in footer
```
